# Generated by Django 4.2.5 on 2023-10-30 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('age', models.PositiveSmallIntegerField()),
                ('course', models.PositiveSmallIntegerField()),
                ('student_id', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('dt_info', models.TextField(blank=True, null=True)),
                ('student_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.author')),
            ],
        ),
    ]
